### ISSUE TITLE
Customizing Opro::Oauth::TokenController

### ISSUE THREAD

**Issue by bodrovis** [opro/opro#52]
Hello!

Currently I am writing an article about opro (probably you've seen it on Sitepoint's Trello board). It seems that TokenController is not meant to be customizable, however what I wanted to do is to return a bit more information when presenting a token, for example, some info about a user who is authenticating. https://github.com/opro/opro/blob/ecffe22e777bb9cacfedd55d059a2ca3cb163a05/app/controllers/opro/oauth/token_controller.rb#L15 Like, you know, when authenticating via Twitter we get a pretty big hash of various data about a user apart from token (name, avatar, followers count etc). I could've created some custom controller action and after receiving a token just make individual request there, but that seems a bit cumbersome to me.

Maybe you could recommend something? I'd be very grateful. :)

**Comment by bodrovis** [comment]
Can't we just do something like this https://github.com/opro/opro/blob/master/lib/opro/rails/routes.rb#L10 to allow customizing

```ruby
mount_opro_oauth controllers: {oauth_token: 'oauth/token'}
```

**Comment by schneems** [comment]
Sorry for radio silence, i've been pretty busy. 

You can see an example of a controller being overwritten https://github.com/opro/opro_rails_demo/blob/master/app/controllers/oauth/client_apps_controller.rb and https://github.com/opro/opro_rails_demo/blob/41d7795bbd9d4d3604bc084d040ee3e32b8562b4/config/routes.rb#L5

So, yes you would need to over-write the controller action that returns data, to extend it with some custom json. 

Here is where we are building the json and returning it after a successful auth https://github.com/opro/opro/blob/ecffe22e777bb9cacfedd55d059a2ca3cb163a05/app/controllers/opro/oauth/token_controller.rb#L9-L23 (I think).

It would be hard to change that hash without re-implementing all of the logic. If you wanted to modify opro to make this easier, the easiest way would be to put that hash generation in another method like `generate_access_token_hash` and then you could easily extend it.

```ruby
class MyCustomTokenController < Opro::Oauth::TokenController
  def generate_access_token_hash(auth_grant)
    (super auth_grant).merge(email: "whatever", username: "whatever")
  end
end
```

Is that kinda what you're looking for? That would require a change and cutting a new release, but it seems pretty easy.

I'm a bit curious why you picked opro/ Most people tend to favor https://github.com/doorkeeper-gem/doorkeeper.

**Comment by bodrovis** [comment]
@schneems Thank you for detailed explanations :) Yeah, I understand how this all can be redefined, but currently I haven't found a way to actually redefine the route to point to a new TokenController. Therefore I submitted this PR https://github.com/opro/opro/pull/54 The basic idea is that anyone can point route to a new token controller and then redefine the `.json` view as needed. For me the befit of using a separate `.json` view is that I can only change it without touching controller's method at all (and without introducing any additional methods) for example like this:

```
class TokenController < Opro::Oauth::TokenController
  def create
    super
    render 'auth/create' # points to my custom view
  end
end
```

Tomorrow I am going to update my source code for the article and demonstrate that idea a bit more clearly.

Of course I've heard about Doorkeeper but as long as my goal is to cover various solutions, I am writing about everything that seems viable to me :) Probably the article will be composed of two parts, I'll send a link then.

**Comment by bodrovis** [comment]
Okay, so here is how can it work.

* I create a new "server" app and redefine a route to point to my new TokenController https://github.com/bodrovis/Sitepoint-source/blob/master/Auth_Provider_with_Opro/OproServer/config/routes.rb#L4
* I create a new TokenController. No methods have to be redefined because in my case I only need a custom view https://github.com/bodrovis/Sitepoint-source/blob/master/Auth_Provider_with_Opro/OproServer/app/controllers/oauth/token_controller.rb#L1
* I create a custom view and add any fields as necessary https://github.com/bodrovis/Sitepoint-source/blob/master/Auth_Provider_with_Opro/OproServer/app/views/oauth/token/create.json.jbuilder#L5

The whole set up (server and client) is here https://github.com/bodrovis/Sitepoint-source/tree/master/Auth_Provider_with_Opro. To me this seems pretty convenient, however I might've missed something.
